platform :ios, '7.0'

# pod 'GDRealtime', '~> 0.3.0'
pod 'PSStackedView', '~> 1.0'
pod 'GDRealtime', :git => 'https://github.com/goodow/GDRealtime.git'
pod 'MKNetworkKit', '~> 0.87'
pod 'vfrReader', '~> 2.6.2'
# pod 'GDJson', :git => 'https://github.com/goodow/GDJson.git'
